name: Lint and Test

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint
        uses: py-actions/flake8@v1
        with:
          max-line-length: "88"

# TODO: implement tests
#      - name: Test
#        run: |
#          pytest --cov-report term-missing --cov=backmeup tests/