name: Lint and Test

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools wheel
          pip install -r requirements.txt
          pip install -r requirements_test.txt
          pip install .

      - name: Lint
        uses: py-actions/flake8@v1
        with:
          max-line-length: "88"

      - name: Mypy
        run: mypy clifs/

      - name: Test
        run: |
          pytest --cov-report term-missing --cov=clifs tests/