name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools wheel
          pip install -r requirements.txt
          pip install -r requirements_test.txt
      
      - name: isort
        uses: jamescurtin/isort-action@master

      - name: black
        uses: psf/black@stable
      
      - name: flake8
        uses: py-actions/flake8@v1
        with:
          max-line-length: "88"
      
      - name: Mypy
        run: mypy clifs/
