name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools wheel
          pip install -r requirements.txt
          pip install -r requirements_test.txt
      
      - name: isort
        run: isort --check .

      - name: black
        run: black --check .
      
      - name: flake8
        run: pflake8 .

      - name: pylint
        run: pylint clifs/
      
      - name: Mypy
        run: mypy clifs/
