name: Hatch-Release
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "release type"
        required: true
        default: dev
        type: choice
        options:
          - major
          - minor
          - patch
          - pre
          - dev
jobs:
  Release:
    runs-on: ubuntu-latest
    if: ${{ always() && format('refs/heads/{0}', github.event.repository.default_branch) == github.ref }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.0.0
        with:
          token: ${{secrets.PAT}}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install Hatch
        run: |
          python -m pip install --upgrade pip 
          pip install hatch

      - name: Bump version and update changelog
        run: |
          VERSION=`hatch version`
          hatch version ${{ inputs.log_level }}
          NEW_VERSION=`hatch version`
          now=$(date +"%b. %d, %Y")
          [[ -f CHANGELOG.md ]] && \
          sed -i \
          "s/## Unreleased/## $NEW_VERSION - $now\n---------------------/" CHANGELOG.md
          [[ -f CHANGELOG.md ]] && sed -i '3i ## Unreleased \n\n' CHANGELOG.md

      - name: Tag and push changes
        run: |
          git add -a
          git commit -m "bump version: $VERSION → $NEW_VERSION"
          git tag $NEW_VERSION
          git push && git push --tags
